sudo: required

language: python

install:
  # install tools
  - pip install sphinx
  - pip install recommonmark
  - pip install sphinx_rtd_theme
  - gem install html-proofer

script:
  - curl -Vv
  - sphinx-build docs build
  - htmlproofer --url-ignore="#" --file-ignore build/search.html build
