sudo: required

language: ruby
rvm:
  - 2.3.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  # Node.js
  - sudo apt-get install -y build-essential
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install gitbook-cli -g
  # html proofer
  - gem install html-proofer

script:
  - gitbook install
  - gitbook build
  - htmlproofer _book
