sudo: required

language: node_js
node_js: "node"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  # RVM
  - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - \curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer | bash -s stable --ruby
  # html proofer
  - gem install html-proofer
  # gitbook
  - npm install gitbook-cli -g

script:
  - gitbook install
  - gitbook build
  - htmlproofer _book
